# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
   "iPhone 6",
])

languages([
  "en-US",
])

launch_arguments([
    "-hello HELLO"
])

# The name of the scheme which contains the UI Tests
scheme "json_test"

output_simulator_logs true

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

# clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
project "../json_test.xcodeproj"

localize_simulator true
